services:
  api-service:
    container_name: api-service
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend-service:
    container_name: frontend-service
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
