services:
  json-server:
    container_name: json-server
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network

  react-app:
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: dockerfile
    ports:
      - "8080:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
